votes-requiered: 6

#Time until the mayor will be derank if he quit the server, in minutes
mayor-derank-delay: 5
derank-mayor-on-death: true
derank-mayor-on-quit: true

#Time until a player will be derank if he quit the server, in minutes
player-derank-delay: 5
derank-players-on-death: false
derank-players-on-quit: false

default-rank: "Citoyen"

#You can use %player% to write the player's name, %rank% to write the rank and the color codes like &4 or &e
#You can use %target% only in YES/NO_BROADCAST and TARGET_OFFLINE messages
#You can use %mayor% only in MAYOR_ALREADY_EXISTS and MAYOR_DERANKED messages
#You can use %time% only in MAYOR_DERANKED message

#If you want disable a message, set it to ""

RANK_NOT_FOUND: "&cLe grade &e%rank%&c n'existe pas."
RANK_ALREADY_SAVED: "&cLe grade &e%rank%&c est déjà dans la liste."
VOTE_BROADCAST: "&e%player%&a se propose pour être &e%rank%&a ! Votez avec /vote <oui | non> %player%."
YES_BROADCAST: "&a%player% a voté &eoui&a pour &e%target%&a."
NO_BROADCAST: "&a%player% a voté &cnon&a pour &e%target%&a."
PLAYER_RANKUP: "&e%player%&a a été promu &e%rank%"
TARGET_OFFLINE: "&eMtarget%c n'est pas connecté(e)."
RANK_ADDED: "&aLe grade &e%rank%&a a été &eajouté&a à la liste."
RANK_REMOVED: "&aLe grade &e%rank%&a a été &csupprimé&a de la liste."
ALREADY_VOTED: "&cVous avez déjà voté !"
CANT_VOTE_YOURSELF: "&cVous ne pouvez pas voter pour vous."
MAYOR_ALREADY_EXISTS: "&cIl y a déjà un maire: &e%mayor%&c."
MAYOR_QUIT_DERANKED: "&a&lLe maire &e%mayor%&a&l est resté déconnecté %time%mins et a été dégradé !"
MAYOR__DEATH_DERANKED: "&a&lLe maire &e%mayor%&a&l est mort et a été dégradé !"
PLAYER_QUIT_DERANKED: "&a&lLe joueur &e%player%&a&l est mort et a été dégradé !"
PLAYER_DEATH_DERANKED: "&a&lLe joueur &e%player%&a&l est mort et a été dégradé !"


mayor: " "

ranks: